### ISSUE TITLE
Docker hub build failing on unidata/jupyter-singleuser

### ISSUE THREAD

**Issue by dlebauer** [Unidata/Unidata-Dockerfiles#24]
the unidata/jupyter-singleuser dockerhub build is failing https://hub.docker.com/r/unidata/jupyter-singleuser/builds/bdzshwf3c3ckzbl2huzmdbk/ (also fails at mybinder.org)

But it looks like the jupyter-singleuser/Dockerfile is no longer in this repository (last seen at 0596bc63e3ad41d3fc5daa2d54ec5637ed4dd938; last successful build 3 months ago https://hub.docker.com/r/unidata/jupyter-singleuser/builds/bbpugwgqvoooigxjr6hv6ps/)

Has this been replaced by another docker container? I was looking for a docker container that I could use with Jupyter + python netcdf4 at a workshop. Which one would be the best option?

**Comment by dopplershift** [comment]
You should look at the [Unidata/python-docker](https://github.com/Unidata/python-docker) repository. It doesn't currently have any pre-populated notebooks, but that should be remedied shortly. The docker hub repo is [here.](https://hub.docker.com/r/unidata/python/)

These are based on the scipy stack container maintained by the [Jupyter project](https://github.com/jupyter/docker-stacks).

**Comment by julienchastang** [comment]
(FYI, I wrote this before @dopplershift's response, but I am posting it anyway :-) )

Thanks for pointing this out, and, yes, this is indeed somewhat in limbo. That Jupyter folder, was unfortunately, out-of-date and had not been maintained in some time. We (@dopplershift, @jrleeman) are aiming to revamp this area shortly with [Unidata/python-general/issues/8](https://github.com/Unidata/python-general/issues/8). 

In order to get you going quickly in the interim, there are various options:

- Skip the container route and use conda directly coupled with the https://github.com/Unidata/unidata-python-workshop, and https://unidata.github.io/unidata-python-workshop/installation.html
-  MyBinder, (though I have had mixed results on the reliability of MyBinder, and wonder if it would be appropriate for a workshop setting): http://mybinder.org/repo/Unidata/unidata-python-workshop
- If wanting to use a container, there is https://github.com/Unidata/Unidata-Dockerfiles/tree/master/python (which is not available on Dockerhub, but you could build yourself). Since running Jupyter in a container, you may have to invest a small amount time with the server settings with respect to security (`.jupyter/jupyter_notebook_config.py` stuff). This folder will eventually go away too as  [Unidata/python-general/issues/8](https://github.com/Unidata/python-general/issues/8) matures.
- Wait for [Unidata/python-general/issues/8](https://github.com/Unidata/python-general/issues/8) 

On a related note, it has been on my list of things to do to better maintain our presence on dockerhub which, as you have discovered, is crufty at this point with a variety of active and dead projects, but with no way of distinguishing the two. Your note makes me realize this should be on the front burner.
